require('dotenv').config();
const fs=require('fs');const path=require('path');const crypto=require('crypto');const express=require('express');
const {Client,GatewayIntentBits,Partials,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,SlashCommandBuilder,PermissionsBitField,REST,Routes}=require('discord.js');
const TOKEN=process.env.DISCORD_TOKEN||process.env.TOKEN;const CLIENT_ID=process.env.CLIENT_ID||process.env.DISCORD_CLIENT_ID;const GUILD_ID=process.env.GUILD_ID||'';const PORT=process.env.PORT||10000;
const RECRUT_CHANNEL_ID=process.env.RECRUT_CHANNEL_ID||'';const CANDIDATURA_CHANNEL_ID=process.env.CANDIDATURA_CHANNEL_ID||'';const LOG_CHANNEL_ID=process.env.LOG_CHANNEL_ID||'';
const app=express();app.use(express.json({limit:'2mb'}));app.use(express.static(__dirname));
const DB=path.join(__dirname,'database');if(!fs.existsSync(DB))fs.mkdirSync(DB,{recursive:true});
function load(n,f){try{return fs.existsSync(path.join(DB,n))?JSON.parse(fs.readFileSync(path.join(DB,n),'utf8')):f}catch{return f}}
function save(n,v){try{fs.writeFileSync(path.join(DB,n),JSON.stringify(v,null,2))}catch(e){console.error('DB',e.message)}}
let db={points:load('points.json',{}),xp:load('xp.json',{}),roblox:load('roblox.json',{}),recruitments:load('recruitments.json',[]),applications:load('applications.json',[]),support:load('support.json',[]),posts:load('posts.json',[]),codes:load('codes.json',{})};
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildPresences],partials:[Partials.Channel,Partials.GuildMember,Partials.Message]});
const roles=['LDR','SB-LDR','ADM','CMDT','MOD','SUP','TRN-STAFF','INF','EDT','ORG','REC','BSTR','PCR','MBRS','NVT'];
const roleNames={LDR:'🔴 [LDR] Alfa','SB-LDR':'🍷 [SB-LDR] Beta',ADM:'🟣 [ADM] Administrador',CMDT:'🔷 [CMDT] Comandante',MOD:'🔵 [MOD] Moderador',SUP:'🟢 [SUP] Suporte', 'TRN-STAFF':'🌱 [TRN-STAFF] Treinamento',INF:'🌸 [INF] Influenciador',EDT:'💗 [EDT] Editor',ORG:'🩵 [ORG] Organizador',REC:'🫒 [REC] Recrutador',BSTR:'🟠 [BSTR] Booster',PCR:'🔹 [PCR] Parceiro',MBRS:'⚪ [MBRS] Membro',NVT:'⚫ [NVT] Novato'};
function addXP(id,n=10){db.xp[id]=(db.xp[id]||0)+n;save('xp.json',db.xp)}function level(id){return Math.floor(Math.sqrt((db.xp[id]||0)/25))+1}
function points(id){return db.points[id]||0}function addPoints(id,n){db.points[id]=points(id)+n;save('points.json',db.points)}
function isStaff(m){return m?.permissions?.has(PermissionsBitField.Flags.ManageMessages)||m?.permissions?.has(PermissionsBitField.Flags.ManageGuild)||m?.roles?.cache?.some(r=>/\[(LDR|SB-LDR|ADM|CMDT|MOD|SUP|ORG|REC)\]/i.test(r.name))}
const PERMISSIONS={
 recrutamento:['REC','SUP','MOD','CMDT','ADM','SB-LDR','LDR'], candidaturas:['REC','MOD','CMDT','ADM','SB-LDR','LDR'], aprovar:['REC','CMDT','ADM','SB-LDR','LDR'], recusar:['REC','CMDT','ADM','SB-LDR','LDR'],
 aviso:['MOD','CMDT','ADM','SB-LDR','LDR'], silenciar:['MOD','CMDT','ADM','SB-LDR','LDR'], dessilenciar:['MOD','CMDT','ADM','SB-LDR','LDR'], expulsar:['CMDT','ADM','SB-LDR','LDR'], banir:['ADM','SB-LDR','LDR'], desbanir:['ADM','SB-LDR','LDR'], limpar:['MOD','CMDT','ADM','SB-LDR','LDR'], trancar:['MOD','CMDT','ADM','SB-LDR','LDR'], destrancar:['MOD','CMDT','ADM','SB-LDR','LDR'], histórico:['MOD','CMDT','ADM','SB-LDR','LDR'],
 cargo:['ADM','SB-LDR','LDR'], 'dar-cargo':['ADM','SB-LDR','LDR'], 'remover-cargo':['ADM','SB-LDR','LDR'], setcargo:['ADM','SB-LDR','LDR'], config:['ADM','SB-LDR','LDR'], logs:['ADM','SB-LDR','LDR'], painel:['ADM','SB-LDR','LDR'], anunciar:['ADM','CMDT','SB-LDR','LDR'], embed:['ADM','SB-LDR','LDR'],
 evento:['ORG','CMDT','ADM','SB-LDR','LDR'], jogatina:['ORG','CMDT','ADM'], resenha:['ORG','CMDT','ADM'], chamada:['ORG','REC','CMDT','ADM'], presença:['ORG','REC','CMDT','ADM'], 'pontos-add':['ORG','REC','CMDT','ADM'], 'pontos-remove':['CMDT','ADM','SB-LDR','LDR'], recompensa:['ADM','CMDT','SB-LDR','LDR'], 'conquista-add':['ORG','CMDT','ADM'],
 boasvindas:['ADM','SB-LDR','LDR'], entrada:['ADM','SB-LDR','LDR'], saida:['ADM','SB-LDR','LDR'], autocargo:['ADM','SB-LDR','LDR'], verificação:['ADM','CMDT','SB-LDR','LDR'], 'chamada-auto':['ADM','CMDT','ORG'], 'anuncio-auto':['ADM','SB-LDR','LDR']
};
function hasRoleCode(m,codes){if(m?.permissions?.has(PermissionsBitField.Flags.Administrator))return true;return m?.roles?.cache?.some(r=>codes.includes(Object.keys(roleNames).find(k=>roleNames[k]===r.name)||'__NONE__'))||m?.roles?.cache?.some(r=>codes.some(c=>r.name.includes(`[${c}]`)));}
function canRun(m,command){const need=PERMISSIONS[command];return !need||hasRoleCode(m,need);}

function findChannel(guild,id,name){return (id&&guild.channels.cache.get(id))||guild.channels.cache.find(c=>c.name.toLowerCase().includes(name)&&c.isTextBased())}
async function sendRecruitment(data){const guild=client.guilds.cache.get(GUILD_ID)||client.guilds.cache.first();if(!guild)return false;const ch=findChannel(guild,RECRUT_CHANNEL_ID,'recrut');if(!ch)return false;const e=new EmbedBuilder().setColor(0xa855f7).setTitle('🦇 Novo Recrutamento NVB').addFields(Object.entries(data).slice(0,10).map(([k,v])=>({name:k,value:String(v||'N/A').slice(0,1024),inline:false}))).setTimestamp();await ch.send({embeds:[e]});return true}
async function sendApplication(data){const guild=client.guilds.cache.get(GUILD_ID)||client.guilds.cache.first();if(!guild)return false;const ch=findChannel(guild,CANDIDATURA_CHANNEL_ID,'candidat');if(!ch)return false;const e=new EmbedBuilder().setColor(0x8b5cf6).setTitle(`📋 Candidatura • ${data.cargo||'NVB'}`).setDescription(Object.entries(data).map(([k,v])=>`**${k}:** ${String(v||'N/A').slice(0,900)}`).join('\n')).setTimestamp();await ch.send({embeds:[e]});return true}
const COMMAND_REGISTER_NAME={"histórico":"historico","presença":"presenca","verificação":"verificacao"};
const COMMAND_CANONICAL_NAME={historico:"histórico",presenca:"presença",verificacao:"verificação"};
function cmd(name,desc){return new SlashCommandBuilder().setName(COMMAND_REGISTER_NAME[name]||name).setDescription(desc)}
const commands=[
cmd('nvb','🦇 Abrir o painel principal NVB'),cmd('perfil','🪪 Ver seu perfil NVB'),cmd('roblox','🎮 Ver ou registrar seu Roblox').addStringOption(o=>o.setName('nick').setDescription('Nick Roblox').setRequired(false)),cmd('avatar','🖼️ Ver seu avatar'),cmd('cargos','🏷️ Ver seus cargos'),cmd('conquistas','🏆 Ver suas conquistas'),cmd('nivel','⭐ Ver seu nível'),cmd('pontos','🪙 Ver seus pontos'),cmd('ranking','🏆 Ver ranking'),cmd('ajuda','🤖 Ver ajuda'),
cmd('recrutamento','🩸 Abrir recrutamento'),cmd('candidatura','📋 Enviar candidatura').addStringOption(o=>o.setName('cargo').setDescription('Cargo').setRequired(true).addChoices(...[['ADM','🟣 Administrador'],['CMDT','🔵 Comandante'],['MOD','🔷 Moderador'],['SUP','🟢 Suporte'],['ORG','🩵 Organizador'],['REC','🟢 Recrutador'],['INF','🩷 Influenciador']].map(([value,name])=>({name,value})))),cmd('candidaturas','📋 Ver candidaturas'),cmd('aprovar','✅ Aprovar candidatura').addStringOption(o=>o.setName('id').setDescription('ID da candidatura').setRequired(true)),cmd('recusar','❌ Recusar candidatura').addStringOption(o=>o.setName('id').setDescription('ID da candidatura').setRequired(true)),cmd('status','📊 Ver status de candidatura'),
cmd('aviso','⚠️ Emitir aviso').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addStringOption(o=>o.setName('motivo').setDescription('Motivo').setRequired(true)),cmd('silenciar','🔇 Silenciar usuário').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addStringOption(o=>o.setName('motivo').setDescription('Motivo').setRequired(false)),cmd('dessilenciar','🔊 Remover silêncio').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)),cmd('expulsar','👢 Expulsar usuário').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addStringOption(o=>o.setName('motivo').setDescription('Motivo').setRequired(false)),cmd('banir','🔨 Banir usuário').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addStringOption(o=>o.setName('motivo').setDescription('Motivo').setRequired(false)),cmd('desbanir','🔓 Desbanir usuário').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)),cmd('limpar','🧹 Limpar mensagens').addIntegerOption(o=>o.setName('quantidade').setDescription('Quantidade').setRequired(true).setMinValue(1).setMaxValue(100)),cmd('trancar','🔒 Trancar canal'),cmd('destrancar','🔓 Destrancar canal'),cmd('histórico','📜 Ver histórico'),
cmd('skin','🎨 Ver sistema de skins'),cmd('skin-ia','🤖 Gerar skin com IA').addStringOption(o=>o.setName('estilo').setDescription('Estilo').setRequired(true)),cmd('criar-skin','🎨 Criar skin'),cmd('editar-skin','✏️ Editar skin'),cmd('analisar-skin','🔎 Analisar skin'),cmd('melhorar-skin','✨ Melhorar skin'),cmd('skin-nvb','🦇 Skin NVB'),cmd('template-skin','📐 Template de skin'),cmd('avaliar-skin','⭐ Avaliar skin'),cmd('salvar-skin','💾 Salvar skin'),cmd('skins','🖼️ Listar skins'),cmd('skin-atual','🖼️ Ver skin atual'),cmd('skin-random','🎲 Skin aleatória'),cmd('skin-personalizada','🧩 Skin personalizada'),
cmd('cargo','🏷️ Consultar cargo').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(false)),cmd('dar-cargo','➕ Dar cargo').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addRoleOption(o=>o.setName('cargo').setDescription('Cargo').setRequired(true)),cmd('remover-cargo','➖ Remover cargo').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addRoleOption(o=>o.setName('cargo').setDescription('Cargo').setRequired(true)),cmd('setcargo','⚙️ Definir cargo').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addRoleOption(o=>o.setName('cargo').setDescription('Cargo').setRequired(true)),cmd('config','⚙️ Configuração NVB'),cmd('logs','📜 Logs NVB'),cmd('painel','🦇 Painel administrativo'),cmd('anunciar','📢 Fazer anúncio').addStringOption(o=>o.setName('mensagem').setDescription('Mensagem').setRequired(true)),cmd('embed','🧩 Criar embed').addStringOption(o=>o.setName('titulo').setDescription('Título').setRequired(true)).addStringOption(o=>o.setName('descricao').setDescription('Descrição').setRequired(true)),
cmd('evento','🎉 Criar evento').addStringOption(o=>o.setName('nome').setDescription('Nome').setRequired(true)),cmd('jogatina','🎮 Criar jogatina').addStringOption(o=>o.setName('jogo').setDescription('Jogo').setRequired(true)),cmd('resenha','💬 Criar resenha').addStringOption(o=>o.setName('tema').setDescription('Tema').setRequired(true)),cmd('chamada','📣 Fazer chamada'),cmd('presença','🟢 Registrar presença'),cmd('pontos-add','➕ Adicionar pontos').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addIntegerOption(o=>o.setName('quantidade').setDescription('Pontos').setRequired(true)),cmd('pontos-remove','➖ Remover pontos').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addIntegerOption(o=>o.setName('quantidade').setDescription('Pontos').setRequired(true)),cmd('recompensa','🎁 Registrar recompensa').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addStringOption(o=>o.setName('recompensa').setDescription('Recompensa').setRequired(true)),cmd('conquista-add','🏆 Adicionar conquista').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)).addStringOption(o=>o.setName('conquista').setDescription('Conquista').setRequired(true)),
cmd('boasvindas','👋 Configurar boas-vindas'),cmd('entrada','🚪 Configurar entrada'),cmd('saida','🚪 Configurar saída'),cmd('autocargo','🏷️ Configurar autocargo'),cmd('verificação','✅ Configurar verificação'),cmd('chamada-auto','📣 Configurar chamada automática'),cmd('anuncio-auto','📢 Configurar anúncio automático')
].map(x=>x.toJSON());
function panel(){return {embeds:[new EmbedBuilder().setColor(0x8b5cf6).setTitle('🦇 QG NVB • Nytheris Vampyre Bloodline').setDescription('Escolha uma área do seu QG.').addFields({name:'🪪 Meu perfil',value:'Dados do membro',inline:true},{name:'🎮 Meu Roblox',value:'Roblox vinculado',inline:true},{name:'🖼️ Meu avatar',value:'Avatar/skin',inline:true},{name:'🏷️ Meus cargos',value:'Cargos',inline:true},{name:'🏆 Minhas conquistas',value:'Conquistas',inline:true},{name:'⭐ Nível',value:'XP e nível',inline:true},{name:'🪙 Pontos',value:'Saldo',inline:true},{name:'🏆 Ranking',value:'Classificação',inline:true},{name:'🟢 Online',value:'Membros online',inline:true})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('nvb_perfil').setLabel('🪪 Meu perfil').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('nvb_roblox').setLabel('🎮 Meu Roblox').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('nvb_avatar').setLabel('🖼️ Meu avatar').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('nvb_cargos').setLabel('🏷️ Meus cargos').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('nvb_conquistas').setLabel('🏆 Minhas conquistas').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('nvb_nivel').setLabel('⭐ Nível').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('nvb_pontos').setLabel('🪙 Pontos').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('nvb_ranking').setLabel('🏆 Ranking').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('nvb_online').setLabel('🟢 Online').setStyle(ButtonStyle.Secondary))]};}

const sessions=new Map();
function normalize(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
function newEntryCode(){return 'NVB-'+crypto.randomBytes(4).toString('hex').toUpperCase()}
function createSession(user){const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{...user,createdAt:Date.now()});return token}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const token=h.slice(7);const s=sessions.get(token);if(!s)return null;if(Date.now()-s.createdAt>7*24*60*60*1000){sessions.delete(token);return null}return s}
function requireAuth(req,res){const u=auth(req);if(!u){res.status(401).json({ok:false,error:'Sessão expirada. Entre novamente no QG.'});return null}return u}
function roleCodeFromName(name){const m=String(name||'').match(/\[([^\]]+)\]/);return m?m[1]:null}
function roleForCargo(guild,cargo){const code=String(cargo||'').toUpperCase();return guild?.roles?.cache?.find(r=>roleCodeFromName(r.name)===code)||guild?.roles?.cache?.find(r=>normalize(r.name).includes(normalize(cargo)))||null}
async function getGuildUser(user){const guild=client.guilds.cache.get(GUILD_ID)||client.guilds.cache.first();if(!guild)return {userId:user.userId||'',discord:user.discord||'',principal:user.principal||'',roblox:user.roblox||'',roles:[],points:points(user.userId||''),level:level(user.userId||''),xp:db.xp[user.userId||'']||0};let member=null;if(user.userId){member=await guild.members.fetch(user.userId).catch(()=>null)}if(!member&&user.discord){member=guild.members.cache.find(m=>normalize(m.user.username)===normalize(user.discord)||normalize(m.user.tag)===normalize(user.discord)||normalize(m.displayName)===normalize(user.discord))||null}const id=member?.id||user.userId||'';const rec=[...db.recruitments].reverse().find(x=>normalize(x.discord)===normalize(member?.user.username||user.discord)||normalize(x.principal)===normalize(user.principal)||x.discordId===id);return {userId:id,discord:member?.user?.username||user.discord||'',principal:user.principal||'',roblox:db.roblox[id]?.nick||user.roblox||'',roles:member?.roles?.cache?.filter(r=>r.id!==guild.id).map(r=>r.name)||[],points:points(id),level:level(id),xp:db.xp[id]||0,recruitment:rec||null}}

client.once('ready',async()=>{console.log(`NVB BOT online: ${client.user.tag}`);try{const rest=new REST({version:'10'}).setToken(TOKEN);await rest.put(GUILD_ID?Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID):Routes.applicationCommands(CLIENT_ID),{body:commands});console.log(`${commands.length} comandos NVB registrados.`)}catch(e){console.error('Registro:',e.message)}});

client.on('interactionCreate',async i=>{try{
if(i.isButton()&&i.customId.startsWith('nvb_')){const a=i.customId.slice(4),id=i.user.id;let content='';if(a==='perfil')content=`🪪 **Meu perfil**\nDiscord: ${i.user}\nNível: ${level(id)}\nPontos: ${points(id)}`;else if(a==='roblox')content=`🎮 **Meu Roblox**\n${db.roblox[id]?.nick||'Nenhum Roblox vinculado. Use /roblox nick:SeuNick'}`;else if(a==='avatar')content='🖼️ **Meu avatar**\nUse /skin-ia ou /skin para o sistema de skins.';else if(a==='cargos')content=`🏷️ **Meus cargos**\n${i.member?.roles?.cache?.filter(r=>r.id!==i.guild.id).map(r=>r.name).join(', ')||'Nenhum'}`;else if(a==='conquistas')content='🏆 **Minhas conquistas**\nConquistas registradas pelo sistema NVB.';else if(a==='nivel')content=`⭐ **Nível ${level(id)}**\nXP: ${db.xp[id]||0}`;else if(a==='pontos')content=`🪙 **Pontos:** ${points(id)}`;else if(a==='ranking'){const top=Object.entries(db.points).sort((a,b)=>b[1]-a[1]).slice(0,10);content='🏆 **Ranking**\n'+(top.map((x,n)=>`${n+1}. <@${x[0]}> — ${x[1]} 🪙`).join('\n')||'Ainda vazio.')}else if(a==='online')content=`🟢 **Online:** ${i.guild?.members?.cache?.filter(m=>m.presence?.status&&m.presence.status!=='offline').size||0}`;return i.reply({content,ephemeral:true})}
if(!i.isChatInputCommand())return;const raw=i.commandName;const c=COMMAND_CANONICAL_NAME[raw]||raw,m=i.member;addXP(i.user.id,5);
if(c==='nvb')return i.reply(panel());
if(c==='perfil')return i.reply({content:`🪪 **Perfil**\n${i.user}\nNível ${level(i.user.id)} • ${points(i.user.id)} 🪙\nRoblox: ${db.roblox[i.user.id]?.nick||'não vinculado'}`,ephemeral:true});
if(c==='roblox'){const n=i.options.getString('nick');if(n){db.roblox[i.user.id]={...(db.roblox[i.user.id]||{}),nick:n};save('roblox.json',db.roblox);return i.reply(`🎮 Roblox vinculado: **${n}**`)}return i.reply({content:`🎮 Roblox: **${db.roblox[i.user.id]?.nick||'não vinculado'}**`,ephemeral:true})}
if(c==='pontos')return i.reply({content:`🪙 Você possui **${points(i.user.id)} pontos**.`,ephemeral:true});
if(c==='nivel')return i.reply({content:`⭐ Nível **${level(i.user.id)}** • ${db.xp[i.user.id]||0} XP`,ephemeral:true});
if(c==='ranking'){const top=Object.entries(db.points).sort((a,b)=>b[1]-a[1]).slice(0,10);return i.reply('🏆 **Ranking NVB**\n'+(top.map((x,n)=>`${n+1}. <@${x[0]}> — ${x[1]} 🪙`).join('\n')||'Ainda não há pontos registrados.'))}
if(c==='ajuda')return i.reply({content:`🦇 **NVB BOT**\n65 comandos disponíveis. Use **/nvb** para o painel principal.`,ephemeral:true});
if(c==='recrutamento')return i.reply({content:'🩸 Recrutamento NVB\nAcesse o QG: https://qg-nvb-bot.onrender.com/',ephemeral:true});
if(c==='candidatura'){const cargo=i.options.getString('cargo');const data={id:Date.now().toString(),usuario:i.user.id,discordId:i.user.id,discord:i.user.username,cargo,data:new Date().toISOString(),status:'Em análise'};db.applications.push(data);save('applications.json',db.applications);await sendApplication(data).catch(()=>{});return i.reply('📋 Candidatura registrada e encaminhada para a equipe NVB.')}
if(c==='candidaturas'){if(!canRun(m,c))return i.reply({content:'❌ Você não possui o cargo necessário.',ephemeral:true});const rows=db.applications.slice(-15).reverse().map(x=>`**${x.id}** • ${x.discord||x.usuario||'N/A'} • ${x.cargo||'N/A'} • **${x.status||'Em análise'}**`);return i.reply({content:'📋 **Candidaturas NVB**\n'+(rows.join('\n')||'Nenhuma candidatura registrada.'),ephemeral:true})}
if(c==='status'){const mine=db.applications.filter(x=>x.usuario===i.user.id||x.discordId===i.user.id);const rows=mine.slice(-10).reverse().map(x=>`**${x.cargo||'N/A'}** • ${x.status||'Em análise'} • ID ${x.id}`);return i.reply({content:'📊 **Seu status de candidatura**\n'+(rows.join('\n')||'Nenhuma candidatura encontrada.'),ephemeral:true})}
if(c==='aprovar'||c==='recusar'){if(!canRun(m,c))return i.reply({content:'❌ Você não possui o cargo necessário.',ephemeral:true});const id=i.options.getString('id');const a=db.applications.find(x=>x.id===id);if(!a)return i.reply({content:'❌ Candidatura não encontrada.',ephemeral:true});if(c==='recusar'){a.status='Recusada';save('applications.json',db.applications);return i.reply(`❌ Candidatura **${id}** recusada.`)}a.status='Aprovada';a.aprovadaEm=new Date().toISOString();const code=newEntryCode();a.codigo=code;db.codes[code]={discord:a.discord||'',principal:a.principal||'',discordId:a.discordId||a.usuario||'',cargo:a.cargo,status:'Ativo',createdAt:new Date().toISOString()};save('applications.json',db.applications);save('codes.json',db.codes);let dm='';try{const u=await client.users.fetch(a.discordId||a.usuario);if(u){await u.send(`🦇 **NVB • Acesso ao QG aprovado!**\n\nSeu código de entrada é: **${code}**\n\nUse o site oficial para entrar:\nhttps://qg-nvb-bot.onrender.com/\n\nMantenha esse código em segurança.`);dm=' Código enviado por DM.'}}catch(_){}const guild=i.guild;const member=a.discordId?await guild.members.fetch(a.discordId).catch(()=>null):null;if(member&&a.cargo){const r=roleForCargo(guild,a.cargo);if(r&&r.position<guild.members.me.roles.highest.position)await member.roles.add(r).catch(()=>{})}return i.reply(`✅ Candidatura **${id}** aprovada.${dm}\n🔐 Código de entrada gerado: **${code}**`) }
if(!canRun(m,c))return i.reply({content:'❌ Você não possui o cargo necessário para este comando.',ephemeral:true});
if(c==='pontos-add'){const u=i.options.getUser('usuario'),n=Math.max(0,i.options.getInteger('quantidade')||0);addPoints(u.id,n);return i.reply(`🪙 ${n} pontos adicionados a ${u}.`)}
if(c==='pontos-remove'){const u=i.options.getUser('usuario'),n=Math.max(0,i.options.getInteger('quantidade')||0);db.points[u.id]=Math.max(0,points(u.id)-n);save('points.json',db.points);return i.reply(`🪙 ${n} pontos removidos de ${u}.`)}
if(c==='dar-cargo'||c==='remover-cargo'||c==='setcargo'){const u=i.options.getMember('usuario'),r=i.options.getRole('cargo');if(!u||!r)return i.reply({content:'❌ Membro ou cargo não encontrado.',ephemeral:true});if(c==='dar-cargo')await u.roles.add(r);else if(c==='remover-cargo')await u.roles.remove(r);else await u.roles.set([r.id]);return i.reply(`🏷️ Cargo **${r.name}** atualizado para ${u}.`)}
if(c==='limpar'){const n=i.options.getInteger('quantidade');await i.channel.bulkDelete(n,true);return i.reply({content:`🧹 ${n} mensagens removidas.`,ephemeral:true})}
if(c==='trancar'||c==='destrancar'){await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:c==='destrancar'});return i.reply(c==='trancar'?'🔒 Canal trancado.':'🔓 Canal destrancado.')}
if(c==='aviso'){const u=i.options.getUser('usuario'),mot=i.options.getString('motivo');return i.reply(`⚠️ ${u} recebeu um aviso. Motivo: **${mot}**`)}
if(c==='silenciar'){const u=i.options.getMember('usuario');await u.timeout(10*60*1000,i.options.getString('motivo')||'NVB');return i.reply('🔇 Usuário silenciado por 10 minutos.')}
if(c==='dessilenciar'){const u=i.options.getMember('usuario');await u.timeout(null);return i.reply('🔊 Silêncio removido.')}
if(c==='expulsar'){const u=i.options.getMember('usuario');await u.kick(i.options.getString('motivo')||'NVB');return i.reply('👢 Usuário expulso.')}
if(c==='banir'){const u=i.options.getMember('usuario');await u.ban({reason:i.options.getString('motivo')||'NVB'});return i.reply('🔨 Usuário banido.')}
if(c==='desbanir'){await i.guild.members.unban(i.options.getString('id'));return i.reply('🔓 Banimento removido.')}
if(c==='anunciar'){await i.channel.send({content:i.options.getString('mensagem')});return i.reply({content:'📢 Anúncio enviado.',ephemeral:true})}
if(c==='embed'){const e=new EmbedBuilder().setColor(0x8b5cf6).setTitle(i.options.getString('titulo')).setDescription(i.options.getString('descricao'));await i.channel.send({embeds:[e]});return i.reply({content:'🧩 Embed enviado.',ephemeral:true})}
if(c==='conquista-add'){const u=i.options.getUser('usuario'),x=i.options.getString('conquista');addXP(u.id,25);return i.reply(`🏆 Conquista **${x}** registrada para ${u}. +25 XP`)}
if(c==='skin-ia')return i.reply(`🤖 Sistema de IA preparado para o estilo **${i.options.getString('estilo')}**. A geração de imagem continua usando sua configuração de IA.`);
if(c.startsWith('skin')||c==='criar-skin'||c==='editar-skin'||c==='analisar-skin'||c==='melhorar-skin'||c==='avaliar-skin'||c==='salvar-skin'||c==='skins'||c==='template-skin')return i.reply('🎨 Sistema de skins NVB aberto.');
return i.reply(`🦇 **/${c}** executado pelo sistema NVB.`);
}catch(e){console.error('interaction',e);if(i.replied||i.deferred)await i.followUp({content:'❌ Ocorreu um erro ao executar o comando.',ephemeral:true}).catch(()=>{});else await i.reply({content:'❌ Ocorreu um erro ao executar o comando.',ephemeral:true}).catch(()=>{})}});

app.get('/api/status',(req,res)=>res.json({ok:true,bot:client.user?.tag||'NVB BOT',commands:commands.length,discord:!!client.user}));
app.post('/api/recruitment',async(req,res)=>{const d={...req.body,id:Date.now().toString(),data:new Date().toISOString(),status:'Em análise'};db.recruitments.push(d);save('recruitments.json',db.recruitments);const sent=await sendRecruitment(d).catch(()=>false);res.json({ok:true,sent,id:d.id})});
app.post('/api/login',async(req,res)=>{const {discord,principal,codigo}=req.body||{};const valid=db.codes[String(codigo||'').trim().toUpperCase()];if(!valid)return res.status(401).json({ok:false,error:'Código de entrada inválido.'});if(valid.discord&&normalize(valid.discord)!==normalize(discord)&&valid.principal&&normalize(valid.principal)!==normalize(principal))return res.status(401).json({ok:false,error:'Os dados não correspondem ao código de entrada.'});const base={userId:valid.discordId||'',discord:discord||valid.discord,principal:principal||valid.principal,roblox:'',status:valid.status||'Ativo',cargo:valid.cargo||'',codigo};const u=await getGuildUser(base);const token=createSession(u);res.json({ok:true,token,user:u})});
app.get('/api/me',async(req,res)=>{const u=requireAuth(req,res);if(!u)return;res.json({ok:true,user:await getGuildUser(u)})});
app.post('/api/communication',async(req,res)=>{const u=requireAuth(req,res);if(!u)return;const d={...req.body,id:Date.now().toString(),data:new Date().toISOString(),discordId:u.userId,autor:u.discord};db.posts.push(d);save('posts.json',db.posts);const guild=client.guilds.cache.get(GUILD_ID)||client.guilds.cache.first();let sent=false;if(guild){const map={'Chat Geral':['chat-geral','chat'],'Anúncios':['anuncios','anúncios'],'Enquetes':['enquetes','enquete'],'Opiniões':['opinioes','opiniões']};const names=map[d.canal]||[normalize(d.canal).replace(/ /g,'-')];const ch=names.map(n=>findChannel(guild,'',n)).find(Boolean);if(ch){await ch.send({embeds:[new EmbedBuilder().setColor(0x8b5cf6).setTitle(d.titulo||'NVB').setDescription(`**${d.assunto||''}**\n${d.descricao||''}`).setFooter({text:`Enviado pelo QG NVB • ${u.discord}`})]}).catch(()=>{});sent=true}}res.json({ok:true,sent,id:d.id})});
app.post('/api/candidature',async(req,res)=>{const u=requireAuth(req,res);if(!u)return;const d={...req.body,id:Date.now().toString(),data:new Date().toISOString(),discordId:u.userId,discord:u.discord,status:'Em análise'};db.applications.push(d);save('applications.json',db.applications);const sent=await sendApplication(d).catch(()=>false);res.json({ok:true,sent,id:d.id})});
app.get('/api/applications',async(req,res)=>{const u=requireAuth(req,res);if(!u)return;res.json({ok:true,applications:db.applications.filter(x=>x.discordId===u.userId||normalize(x.discord)===normalize(u.discord)).slice(-20).reverse()})});
app.post('/api/points/donate',async(req,res)=>{const u=requireAuth(req,res);if(!u)return;const toRaw=String(req.body.membro||'').trim();const n=Math.floor(Number(req.body.quantidade)||0);if(!toRaw||n<=0)return res.status(400).json({ok:false,error:'Informe membro e quantidade.'});const guild=client.guilds.cache.get(GUILD_ID)||client.guilds.cache.first();let targetId=toRaw.replace(/[<@!>]/g,'');if(!/^\d{15,22}$/.test(targetId)&&guild){const tm=guild.members.cache.find(m=>normalize(m.user.username)===normalize(toRaw)||normalize(m.displayName)===normalize(toRaw));targetId=tm?.id||''}if(!targetId)return res.status(400).json({ok:false,error:'Membro não encontrado.'});if(targetId===u.userId)return res.status(400).json({ok:false,error:'Você não pode doar pontos para si mesmo.'});if(points(u.userId)<n)return res.status(400).json({ok:false,error:'Saldo insuficiente.'});db.points[u.userId]=points(u.userId)-n;db.points[targetId]=points(targetId)+n;save('points.json',db.points);res.json({ok:true,from:points(u.userId),to:points(targetId)})});
app.get('/api/ranking',async(req,res)=>{const guild=client.guilds.cache.get(GUILD_ID)||client.guilds.cache.first();const ranking=Object.entries(db.points).sort((a,b)=>b[1]-a[1]).slice(0,50).map(([id,p])=>({id,name:guild?.members?.cache?.get(id)?.displayName||id,points:p}));res.json({ranking})});
app.post('/api/support',async(req,res)=>{const u=requireAuth(req,res);if(!u)return;const question=String(req.body.pergunta||'').trim();if(!question)return res.status(400).json({ok:false,error:'Escreva sua pergunta.'});const lower=normalize(question);let answer='Recebemos sua pergunta. Ela foi registrada no histórico do QG NVB. Se precisar de análise humana, a equipe poderá continuar o atendimento.';if(lower.includes('ponto'))answer='Para pontos, use o painel Ranking de Pontos. Seu saldo atual é '+points(u.userId)+' 🪙.';else if(lower.includes('recrut'))answer='O recrutamento é enviado para a equipe NVB e fica com status de análise até a decisão da equipe.';else if(lower.includes('candid'))answer='Sua candidatura pode ser acompanhada pelo painel Candidaturas. A decisão é feita pela equipe responsável.';const d={id:Date.now().toString(),question,userId:u.userId,discord:u.discord,data:new Date().toISOString(),answer};db.support.push(d);save('support.json',db.support);const guild=client.guilds.cache.get(GUILD_ID)||client.guilds.cache.first();const ch=findChannel(guild,'','suporte');if(ch)await ch.send({embeds:[new EmbedBuilder().setColor(0x22c55e).setTitle('🆘 Nova solicitação de suporte').setDescription(`**${u.discord}**\n\n${question}`).setTimestamp()]}).catch(()=>{});res.json({ok:true,answer})});
app.get('/api/support/history',async(req,res)=>{const u=requireAuth(req,res);if(!u)return;res.json({ok:true,history:db.support.filter(x=>x.userId===u.userId).slice(-30).reverse()})});
app.get('/api/posts',(req,res)=>res.json(db.posts.slice(-50).reverse()));
app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api/'))return res.sendFile(path.join(__dirname,'index.html'));next()});
app.listen(PORT,()=>console.log(`QG NVB na porta ${PORT}`));
if(TOKEN&&CLIENT_ID)client.login(TOKEN).catch(e=>console.error('Login Discord:',e.message));else console.warn('DISCORD_TOKEN/TOKEN ou CLIENT_ID ausente; site continua online.');
